name: Bug report
description: Сообщите о проблеме с API
labels: [bug]
body:
  - type: input
    id: endpoint
    attributes:
      label: Endpoint
      placeholder: /playlists/{playlistId}
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: HTTP Method
      options:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Минимальные шаги/пэйлоад/заголовки для воспроизведения
      placeholder: |
        1. Отправьте GET запрос на /playlists
        2. Добавьте заголовок Authorization: Bearer <token>
        3. Получите ошибку 500
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Что должно было произойти
      placeholder: Должен вернуться список плейлистов с кодом 200
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / Logs
      description: Что произошло на самом деле (включая логи ошибок)
      placeholder: |
        Получена ошибка 500:
        {
          "error": "Internal server error",
          "message": "Database connection failed"
        }
  - type: input
    id: version
    attributes:
      label: API version
      placeholder: v1.0.0
      description: Версия API, на которой воспроизводится баг
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Окружение (production, staging, local)
      placeholder: production
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Любая дополнительная информация, которая может помочь
      placeholder: Баг воспроизводится только при определенных условиях... 