name: Feature request
description: Suggest an API improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What task/use case is not covered by the current API?
      placeholder: |
        Currently there's no way to get playlist statistics for a user.
        Need to add an endpoint to get track count, total duration, etc.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you propose to solve this problem?
      placeholder: |
        Add new endpoint GET /playlists/{id}/stats that returns:
        - totalTracks: number of tracks
        - totalDuration: total duration in seconds
        - averageRating: average rating
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternative solutions did you consider?
      placeholder: |
        - Add fields to existing endpoint /playlists/{id}
        - Create separate endpoint /stats/playlists/{id}
        - Include statistics in response when getting playlist
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Describe a specific usage scenario
      placeholder: |
        User wants to see overall statistics of their "Favorite Tracks" playlist
        for display in mobile app on the main screen.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Priority for development team
      options:
        - Low
        - Medium
        - High
        - Critical 